### ISSUE TITLE
1.19.4 is broken with modified FastLoad config.

### ISSUE THREAD

**Issue by Kichura** [BumbleSoftware/Fastload#54]
[Dump](https://pastebin.com/raw/jgTpANPh) can be found here, This is the config i am using:

```
chunk_try_limit=25
close_loading_screen_unsafely=true
debug=false
pre_render_radius=3
pregen_chunk_radius=3
```

**Comment by KirboSoftware** [comment]
1.19.4 is still WIP, been busy with other projects and IRL sadly tho, it is in the works! I will keep you up to date once it will be launched

**Comment by KirboSoftware** [comment]
and also, a FYI 1.19.4 broke a few things so don't use the 1.19.3 version for 1.19.4 because they don't work! (Thanks mojang for breaking things, like usual)

and also apologies for the long dev time, I just barely have time myself but I chip at it a small bit at a time so I hope it should be done soon :+1:

**Comment by Kichura** [comment]
No worries, Even if i cannot use fastload at the moment; i can take the time to just wait it out instead of nagging about it but i will stay subscribed in this thread in case any updates are pushed.

**Comment by KirboSoftware** [comment]
I think I've made it work :+1: just waiting for testing results by @StockiesLad and we should be good to go!

**Comment by Kichura** [comment]
Tested fastload 2.7 with same config and it seems to be working properly now.

**Comment by StockiesLad** [comment]
Thanks Joost. This issue seems to be resolved then.

**Comment by KirboSoftware** [comment]
awesome :+1: great to hear
