### ISSUE TITLE
Can´t join Server

### ISSUE THREAD

**Issue by ghost** [BumbleSoftware/Fastload#63]
With newest Version [3.2.0] in singleplayer everything works fine.
When I join a multiplayer server, the message Connecting to server is constantly displayed. I can see the landscape in the background but I can't move etc.

**Comment by AVuTuVA** [comment]
+

**Comment by AVuTuVA** [comment]
The same thing, the inscription "Connecting to the server" enters the server but does not remove

**Comment by StockiesLad** [comment]
Ye this has just been fixed. Will release soon

**Comment by Talbe1** [comment]
I do have the same issue, but I just want to say, you're doing such an amazing job with this mod!
I was in genuine shock when my single player world loaded as quickly as it did. I'm very used to seeing the world loading animation :rofl:.

**Comment by StockiesLad** [comment]
> I do have the same issue, but I just want to say, you're doing such an amazing job with this mod! I was in genuine shock when my single player world loaded as quickly as it did. I'm very used to seeing the world loading animation 🤣.

Thank you! I'm glad you like it!

**Comment by Talbe1** [comment]
Also, I have a little suggestion.

I noticed that in the changelog of the last version (3.2.0) you mentioned that the 441 loading engine was removed entirely, 
and the subtitle, "Modifies the 441 Loading Engine to decrease world loading times" 
doesn't quite "line up" with the newest "feature" of the mod (the removal of the 441 loading engine).

Maybe consider changing the title to something a tiny bit more accurate?
I know that my suggestion is very specific, although, in my opinion, small details in text matter.

The reason for my suggestion is that people who check out the mod (and especially developers too) 
will likely appreciate to know that the 441 loading engine was removed
rather than finding out about it in one of the changelogs
after thinking that the loading engine was only modified.

**Comment by StockiesLad** [comment]
> Also, I have a little suggestion.
> 
> I noticed that in the changelog of the last version (3.2.0) you mentioned that the 441 loading engine was removed entirely, and the subtitle, "Modifies the 441 Loading Engine to decrease world loading times" doesn't quite "line up" with the newest "feature" of the mod (the removal of the 441 loading engine).
> 
> Maybe consider changing the title to something a tiny bit more accurate? I know that my suggestion is very specific, although, in my opinion, small details in text matter.
> 
> The reason for my suggestion is that people who check out the mod (and especially developers too) will likely appreciate to know that the 441 loading engine was removed rather than finding out about it in one of the changelogs after thinking that the loading engine was only modified.

That's actually a good point I would've forgotten about that.

**Comment by StockiesLad** [comment]
Fixed

**Comment by Talbe1** [comment]
Thank you very much for the fix!

Also is the new version (3.3.0) quite a bit faster than 3.2.0?
Because it feels to me like it is. I'm just asking out of curiosity.
It's absolutely **NUTS** how much difference the Fastload mod can make!

**Comment by StockiesLad** [comment]
> Thank you very much for the fix!
> 
> Also is the new version (3.3.0) quite a bit faster than 3.2.0? Because it feels to me like it is. I'm just asking out of curiosity. It's absolutely **NUTS** how much difference the Fastload mod can make!

Ye it is faster. It renders and generates chunks simultaneously now. You can make it even faster by adding C2ME and Sodium if you don't have them already.

Edit: Oops I thought you meant 3.1.0. But for 3.2.0, I'm not too sure. This code cleanup could potentially explain it. But I think if you haven't used 3.2.0 because of the bug,  you might've forgotten the speed and it surprised you again.
