### ISSUE TITLE
Can't join server using ViaFabric

### ISSUE THREAD

**Issue by Felix14-v2** [BumbleSoftware/Fastload#93]
### Description
<details>
 <summary>Just getting stuck on this screen</summary>

![image](https://user-images.githubusercontent.com/75726196/236327286-2aa71f19-771d-4153-9da9-cb36b4bbf48b.png)

</details>

This affects FastLoad starting from 3.2.0, 3.1.1 and below works fine. My main (online) account works fine.

### To Reproduce

1. Install FastLoad
2. Use an account that has not been on the server previously
3. Install [ViaFabricPlus](https://modrinth.com/mod/viafabricplus) ([source](https://github.com/FlorianMichael/ViaFabricPlus))
4. Join to `play.teslacraft.org`
5. See the error

### Demo

<details>
 <summary>FastLoad 3.2.0</summary>

https://user-images.githubusercontent.com/75726196/236335656-bfdf1c56-00f1-45ff-b67a-5156b7041053.mp4

</details>

<details>
<summary>FastLoad 3.3.0+</summary>

https://user-images.githubusercontent.com/75726196/236335878-51a84c5f-2a8e-4ef4-b43c-b07a28ca393d.mp4

</details>

### Log

[latest.log](https://github.com/BumbleSoftware/Fastload/files/11401788/latest.log)

### Environment

Fastload 3.4.0, AuthMe 6.0.0, ViaFabricPlus 2.6.8, Fabric 0.14.19, 1.19.4

**Comment by StockiesLad** [comment]
is this a 3 way incompatibility issue?

**Comment by Felix14-v2** [comment]
I guess no. I used AuthMe just to create a new demo nickname with an empty server profile, besause my main account is verified through the server's forum, so I didn't have to solve the captcha when joining. However, an empty profile had to, and this stage causes a problem with loading.

**Comment by StockiesLad** [comment]
If not, try to recreate this without using via fabric.

**Comment by Felix14-v2** [comment]
> If not, try to recreate this without using via fabric.

Hey, this bug didn't happen with the old version of FastLoad, this isn't ViaFabric's fault.

**Comment by StockiesLad** [comment]
> 

I never said that. I'm asking you to help debug for me to see if the issue occurs due to a possible incompat on each end. Just because it "works" on an old version it doesn't mean necessarily it's my fault. You seem to be blissfully unaware of the huge amount of code changes when 441 was removed. 

I presume you've seen my other responses and that's why you think I'm trying to shirk the responsibility on my end . Instead, I'm actually trying to get in contact with a dev with the bug at hand as I need their knowledge of **their** mod to resolve it on **my end**. How am I supposed to resolve your issue if  I can't nail down which mods that fastload conflicts with. This isn't about pointing fingers, it's about discovering which mod is changing the same code I do.

**Comment by StockiesLad** [comment]
So please again. Try to debug exactly the environment required to properly resolve the issue.

**Comment by Felix14-v2** [comment]
> So please again. Try to debug exactly the environment required to properly resolve the issue.

I guess FastLoad cannot properly handle the data that this particular server is sending in this particular situation. Have you tried to reproduce this bug in your environment? This is already the minimum set of mods with which I can reproduce it.

**Comment by StockiesLad** [comment]
I don't have the time or patience to recreate different environments. I just want everything ready so that when I eventually get to the fixing part of the issue, I can get around to testing immediately.

With that in mind, I need you to clear up something I'm not understanding:
- You said "I guess no" to me asking if it's a 3 way compat issue.
- You say now that that these 3 mods are the minimum amount of mods required.

Can you clarify which one it is?

**Comment by Felix14-v2** [comment]
I clarified this earlier:
> I used AuthMe just to create a new demo nickname with an empty server profile, besause my main account is verified through the server's forum, so I didn't have to solve the captcha when joining. However, an empty profile had to, and this stage causes a problem with loading.

So, in my case, I can't reproduce this error without AuthMe, however anyone else can. It's my fault that I mentioned it. I changed the original message to avoid further misunderstanding.

**Comment by StockiesLad** [comment]
> I clarified this earlier:
> 
> > I used AuthMe just to create a new demo nickname with an empty server profile, besause my main account is verified through the server's forum, so I didn't have to solve the captcha when joining. However, an empty profile had to, and this stage causes a problem with loading.
> 
> So, in my case, I can't reproduce this error without AuthMe, however anyone else can. It's my fault that I mentioned it. I changed the original message to avoid further misunderstanding.

Aha! Thanks. I'll look into to it.

**Comment by StockiesLad** [comment]
Is your config the default settings?

**Comment by StockiesLad** [comment]
hmm upon some testing it doesnt even matter what the settings are. This is definitely a bug on my part and I'm not handling it correctly.

**Comment by StockiesLad** [comment]
ye i just fixed it

**Comment by StockiesLad** [comment]
I'm just doing some refactors right now which is why the update hasnt been released yet
